name: Build main branch

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/$GITHUB_REPOSITORY/everyone-app:$GITHUB_SHA
    - name: GHPR Docker Login
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: <token>
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Publish Docker image
      id: container_publish
      run: |
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/everyone-app:$GITHUB_SHA

