# AZURE_CREDENTIALS obtained with `az ad sp create-for-rbac --name "everyone.app" --sdk-auth --role contributor --scopes /subscriptions/xxxxx/resourceGroups/everyone.app`
name: Publishing

on:
  push:
    branches: [ main ]
env:
  CONTAINER_NAME: everyone-app
  RESOURCE_GROUP: everyone.app
  APP_SERVICE_PLAN: east-us-linux-dev
  WEBAPP_NAME: everyone-app-qa
  DOCKER_REGISTRY_URL: docker.pkg.github.com
  DOCKER_USERNAME: <token>
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}

jobs:
  build_image:
    name: Build the docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_REGISTRY_URL/$GITHUB_REPOSITORY/$CONTAINER_NAME:$GITHUB_SHA
    - name: GHPR Docker Login
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY_URL }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_TOKEN }}
    - name: Publish Docker image
      id: container_publish
      run: |
        docker push $DOCKER_REGISTRY_URL/$GITHUB_REPOSITORY/$CONTAINER_NAME:$GITHUB_SHA
  
  azure_create_app:
    name: Create the Web App on Azure
    runs-on: ubuntu-latest
    
    environment: 
      name: 'qa'

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create the Azure Web App
      run: az webapp create --resource-group $RESOURCE_GROUP --plan $APP_SERVICE_PLAN --name $WEBAPP_NAME --deployment-container-image-name $DOCKER_REGISTRY_URL/$GITHUB_REPOSITORY/$CONTAINER_NAME:$GITHUB_SHA

  azure_set_container:
    name: Set the Web App Container
    runs-on: ubuntu-latest
    needs: [ 'build_image', 'azure_create_app']
    environment: 
      name: 'qa'

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set the Azure Web App Docker registry paramas
      uses: Azure/appservice-settings@v1
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        app-settings-json: |
          [
            {
              "name": "DOCKER_REGISTRY_SERVER_URL",
              "value": "${{ env.DOCKER_REGISTRY_URL }}",
              "slotSetting": false
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_USERNAME",
              "value": "${{ env.DOCKER_USERNAME  }}",
              "slotSetting": false
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
              "value": "${{ env.DOCKER_TOKEN }}",
              "slotSetting": false
            }
          ]

    - name: Set the environment variables
      run: |
        az webapp config appsettings set -g $RESOURCE_GROUP -n ${{ env.WEBAPP_NAME }} --settings APP_ID=${{ secrets.APP_ID }} PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }} NODE_ENV=qa PORT=8080
  
    - name: Load Web App
      timeout-minutes: 2
      continue-on-error: true
      run: curl https://${{ env.WEBAPP_NAME }}.azurewebsites.net



